// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlsjblxgodfvmzmsaggz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsc2pibHhnb2Rmdm16bXNhZ2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzUyMjAsImV4cCI6MjA2MDgxMTIyMH0.TEcGW7gOdZ8HSkZbmn5F2DIMu81SHYD1LtGE8yHAhrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);